# Generated by Django 4.2.5 on 2023-09-29 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('model', models.IntegerField(choices=[(1, 'Lightweight'), (2, 'Middleweight'), (3, 'Cruiserweight'), (4, 'Heavyweight')])),
                ('weight_limit', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500, 'Weight cannot be above 500 Grams')])),
                ('battery_capacity', models.PositiveIntegerField(default=100, editable=False, validators=[django.core.validators.MaxValueValidator(100, 'Battery Percentage Limit is 100%')])),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='Invalid Input', message="Only Letters, Numbers, '-' and '_' are allowed", regex='^[a-zA-Z0-9-_]+$')])),
                ('weight', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='Invalid Code', message="Only Uppercase Letters, Numbers and '_' are allowed", regex='^[A-Z0-9_]+$')])),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
