# Generated by Django 4.2.5 on 2023-09-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DroneAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='drone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DroneAPI.drone'),
            preserve_default=False,
        ),
    ]
