# Generated by Django 4.2.5 on 2023-09-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneAPI', '0002_medications_drone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medications',
            options={'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
    ]
