# Generated by Django 4.2.5 on 2023-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneAPI', '0003_alter_medications_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='Serial Number'),
        ),
    ]
