# Generated by Django 4.2.5 on 2023-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneAPI', '0005_alter_drone_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Serial Number'),
        ),
    ]
