# Generated by Django 4.2.5 on 2023-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneAPI', '0008_alter_medications_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
