# Generated by Django 4.2.5 on 2023-10-01 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneAPI', '0010_dronebatterylevelevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100, 'Battery Percentage Limit is 100%')]),
        ),
    ]
