# Generated by Django 4.2.5 on 2023-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneAPI', '0013_alter_dronemedicationdeliveryevent_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
